### ISSUE TITLE
Ringer plays low, then goes to normal level

### ISSUE THREAD

**Issue by droidkevlar** [Euphoria-OS/Bug-tracker#5]
Do you use Xposed framework? No

Your device: Nexus 6

Which ROM version are you using?
http://euphoria-os.ninja/download.php?file=Nexus%206/Nexus%206%20Builds/Euphoria-OS-1.1-shamu-OFFICIAL-20150512.zip

What kernel are you using - included in the ROM or from another source?
Stock from ROM

What steps will reproduce the problem?
1. Have increasing ring volume disabled
2. Receive call or pick a ringtone

What is the expected result? What do you see instead?
Be same level. Starts off low, then after 1-2s, goes to regular levels.

Is the result seen after a clean flash too?
Yes

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.

**Comment by dsmitty166** [comment]
Unfortuantly this is a bug in the n6.  Every single ROM should have this, with the exception of meanpop, however, he doesn't have any source code published and it isn't really a friendly way of implementing this.  Unless, you know of another AOSP ROM that has this working, I'm not sure it will be fixed right away.

**Comment by droidkevlar** [comment]
Terminus worked and I believe AOSiP did as well. I ran Terminus for 2 days and I did not notice it doing it. Used AOSiP for about a day and dont rem having the issue either. 

https://www.androidfilehost.com/?fid=23991606952600821
https://www.androidfilehost.com/?fid=23991606952601465

**Comment by vded** [comment]
I second that. Especially short ringtones can't be heard, such as Facebook pop, Facebook messenger.

**Comment by tuan2195** [comment]
Clean flashed and problem persists, behavior is the same on stock Nexus 6 builds from Google, have not tested with other ROMs yet.

**Comment by droidkevlar** [comment]
Others have confirmed working as should be on Terminus, Meanpop and AOSiP...hopefully that helps.

**Comment by vded** [comment]
Today was flashing day. Flashed Terminus and AOSiP and in both roms the volume level was at 100% from the first second. Double checked it with Facebook, Messenger, and Gmail.
Please, make it the same in Euphoria. After the above roms came back to Euphoria because it's the one I like the most. The only thing is missing is the sound level at 100% from the start. I missed many notifications because of this bug.

**Comment by dsmitty166** [comment]
Could you please ask Terminus and AOSiP devs where the commit is?  I've looked through their files and nothing stood out to me!  Thanks

**Comment by vded** [comment]
Maybe it's easier for you to ask for some details? 
I'm just a user and I don't think they will give me some answers, and if they do I'm pretty sure I wouldn't understand.

**Comment by droidkevlar** [comment]
I will reach out to the AOSiP team and see if they can help out with this.

**Comment by vded** [comment]
Thank you droidkevlar. Please keep us updated as soon as you have some news.

**Comment by droidkevlar** [comment]
I talked to Kris from AOSiP and she said they dont have the commit for increasing ringer, so that might be an issue. I mentioned that it is a stock N6 issue and she didnt have that issue while on stock. @dsmitty166 maybe try removing the commit for increasing ringer and see if that resolves? Only other thing I know is smali edit to resolve, but I know you dont want to do that. Sorry couldnt be more help guys.

**Comment by tuan2195** [comment]
It has been a long while since I used N6 on stock so I would like to withdraw my comments about it being a bug on the N6 stock. A side note is that Benzo ROM doesn't seem to have this problem as well, while the latest LiquidSmooth and BlissPop do. I am trying to spot a pattern but haven't seen any.

**Comment by droidkevlar** [comment]
@tuan2195 does Benzo, LS, or Blisspop have increasing ringer option? Trying to see if that is the culprit.

**Comment by tuan2195** [comment]
@droidkevlar I'm currently on Benzo. It has the option but adjusting it doesn't do anything. Even setting starting volume to minimum/maximum and the fade time to either ends, the rings will always come up loud from the first second.

**Comment by tungmeister** [comment]
This issue also affects switching to loud speaker when on a call

**Comment by tuan2195** [comment]
Is the issues fixed now? I just flashed Chroma the other day and the issue is no longer there as well. Also the issue is present in the Android M Preview, but since we don't have the source code it's just FYI.

**Comment by vded** [comment]
Nope, not fixed yet. Tried Benzo rom, notifications sound at 100% from first second. Although no other rom is so stable such as Euphoria. It's the only drawback this bug.

**Comment by vded** [comment]
Tried some other ROMs that didn't have this annoying bug. 
These are: crDroid, CyanideL, SOKP
Maybe you can contact the developers of these?

**Comment by vded** [comment]
Hello guys, any progress to this matter? :)

**Comment by vded** [comment]
Downloaded and tested today's update (5th August). Wow, this issue has been resolved!! Thank you so much!! Now all the tones work perfectly! Tested with Facebook's and Facebook's Messenger super short notification tones and can be heard from first second. :+1:

**Comment by dsmitty166** [comment]
Awesome. Not sure that it was intentionally fixed anywhere, but I'm glad to know that it is!!

**Comment by tungmeister** [comment]
The issue is still present when switching to loud speaker on a call.

**Comment by zhou13** [comment]
I do not know whether my problem is as same as this.  The first 0.5 second of nexus after a long idle is abnormal.  Sometime it is missing.  Sometime it is prolonged.  I am on nexus 6.
